### ISSUE TITLE
Feature/Guide request: Make the default english page / rather than /en

### ISSUE THREAD

**Issue by binary64** [UnlyEd/next-right-now#111]
Hi,

I'm wondering if it's possible to make the default entrypoint `/` be in the default language, rather than force us to a subroute for that 1 language only?

Maybe this is best implemented in https://github.com/UnlyEd/next-right-now/tree/gh-pages/guides/i18n as a guide.

**Comment by Vadorequest** [comment]
It's not how I want it to be working for NRN, but it's surely doable.

My reason is that English isn't the default language of my apps, and I much prefer having a `/` that will dynamically detect the best user locale and redirect it.

If you want to have `/` serve english static content, you'll need to disable the `rewrite` rules in `next.config.js` (which rewrites / to /en) and make sure your page uses `en` if no `locale` is provided (but I believe it works like that already, so maybe you just need to disable the rewrite rule only)

**Comment by Vadorequest** [comment]
@binary64 Closing, let me know if it doesn't answer your question.
