### ISSUE TITLE
Internal Server Error when SENTRY_DSN is not defined. 

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#119]
I'm getting `Internal Server Error` when I don't define `SENTRY_DSN` on `.env.local`.

It should be optional.

**Comment by Vadorequest** [comment]
You probably aren't using the latest version because I just tried using `v2-mst-aptd-at-lcz-sty` branch and it worked fine, locally.

**Comment by samuelcastro** [comment]
You're right, it's all working fine, closing.
