### ISSUE TITLE
i18nextInstance prop not being injected on SSG

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#121]
I'm trying to use `i18nextInstance` from `StaticPropsOutput` on SSG/getStaticProps:

```typescript
const commonStaticProps: StaticPropsOutput = await getCommonStaticProps(props);

console.log(commonStaticProps.props.i18nextInstance); // undefined
```

But it's undefined for some reason.

**Comment by Vadorequest** [comment]
That's expected. The `i18nextInstance ` is created by the frontend, not by the backend, it's made available in pages, but not from the server, as it cannot be passed to the frontend (not serialisable).

I've never needed it from the backend, but you should be able to initialise it from the server side if you actually need it there.

**Comment by samuelcastro** [comment]
Yeah, I need it in the server, I'm going to import it directly from the i18n config file. It'd be good to export it from there btw, so anyone can import and use in the server.

Thanks.

**Comment by samuelcastro** [comment]
> That's expected. The `i18nextInstance ` is created by the frontend, not by the backend, it's made available in pages, but not from the server, as it cannot be passed to the frontend (not serialisable).

I'm trying to understand this a little bit more, [here](https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-gcms-lcz-sty/src/components/appBootstrap/MultiversalAppBootstrap.tsx#L153) `i18nextInstance` is being passed down to the server props, so what do you mean it's not in the server?

Sorry the misunderstanding, I'm still trying to use it in the server, without success so far.

**Comment by Vadorequest** [comment]
It's not being passed down from the server to the client there, it's initiated on the server or on the client, depending on the rendering mode.

You should be able to initialise the i18nextInstance on the server by doing `const i18nextInstance: i18n = i18nextLocize(lang, i18nTranslations);` as it's done in https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-gcms-lcz-sty/src/components/appBootstrap/MultiversalAppBootstrap.tsx#L113

**Comment by samuelcastro** [comment]
Yeah, that worked, I just thought that it was being initialized already in the server so I didn't need to do it again, but I guess I was wrong, thanks.

**Comment by Vadorequest** [comment]
Glad you sorted it out. I understand the confusion, I love Next.js but it's not that easy to reason about with all the "magic" that happens behind the wheel, and code being reused for client, server, ssr, ssg, etc. Takes time to master it, and it's very easy to get confused as to what actually happens.
