### ISSUE TITLE
Using TTL 0 for hybrid caching still invalidates cache

### ISSUE THREAD

**Issue by danielr18** [UnlyEd/next-right-now#122]
Should it be` ttl === 0` instead of `timestamp === 0`?
https://github.com/UnlyEd/next-right-now/blob/07c491ad720e23501fea9219f9375ef8f55aec2f/src/utils/caching/hybridCache.ts#L90

**Comment by Vadorequest** [comment]
Probably, I'll take a look today, thanks for reporting!

**Comment by Vadorequest** [comment]
@danielr18 Fixed in #123
