### ISSUE TITLE
Lighthouse Inconsistent Report - Best Practices

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#145]
This is just to document and track the issue described on this issue: https://github.com/GoogleChrome/lighthouse/issues/10876

**Comment by Vadorequest** [comment]
I've found a way to solve this, working on our private NRN fork.

Basically, the bad performance is due to enabling preview mode in staging, I found a way not to do this when Cypress/LightHouse is running, which increases performances.

I'll implement it at some point, it's trivial.

**Comment by samuelcastro** [comment]
Awesome!

**Comment by Vadorequest** [comment]
Done in https://github.com/UnlyEd/next-right-now/pull/214
