### ISSUE TITLE
uuid is not listed in package.json

### ISSUE THREAD

**Issue by crisfcodes** [UnlyEd/next-right-now#155]
https://github.com/UnlyEd/next-right-now/blob/3dc2e77944a06535028c19a656c2914969b04155/src/utils/cookies/UniversalCookiesManager.ts#L7

on the other hand if [uuid](https://www.npmjs.com/package/uuid) is installed  you need to install @types/uuid and call the library as `import { v1 as uuid } from 'uuid'` instead `import uuid from 'uuid/v1';` to avoid problems with TS compiler;

**Comment by Vadorequest** [comment]
Thanks for the feedback, I believe uuid must be installed by another package, otherwise the project wouldn't even compile on Vercel, but it does.

Good catch!

**Comment by Vadorequest** [comment]
@cristian05 Fixed!
