### ISSUE TITLE
Migrate "now" to "vercel"

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#181]
So "now" is deprecated and will stop receiving updates on December 31, 2020.

We need to move from "now" to "vercel".

**Comment by Vadorequest** [comment]
Yes, true. I did try to migrate a few months ago, but noticed the Vercel CLI and Now CLI behaved differently back then.

But it's definitely something I need to do before the end of the year.

**Comment by sovattha** [comment]
I did it on my local branch, it is a pretty straight forward process. Renaming everything that is `now` to `vercel`.
If you did not start, I can try to do it and send a pull request to the branch gh-pages.

**Comment by Vadorequest** [comment]
@sovattha I didn't start yet. Do you use CI/CD with GitHub Actions? Because that's the most critical part to be tested.

It's also a bit more complicated than just updating `gh-pages`. Each `v2-*` branch need to be updated too, separately. (basically, all presets)

But a PR for `gh-pages` is much welcome because documentation needs to be updated too! 👍

**Comment by sovattha** [comment]
I don't know Github Actions enough... better I leave someone else this part.

I would start with the documentation (`gh-pages`) and see if I can contribute on the `v2-*` branches later on.

**Comment by Vadorequest** [comment]
I'll take care of the v2 branches then, thank you for [your PR](https://github.com/UnlyEd/next-right-now/pull/206)!

**Comment by Vadorequest** [comment]
Work has started:
- General documentation: https://github.com/UnlyEd/next-right-now/pull/206 > https://github.com/UnlyEd/next-right-now/pull/212
- GCMS v2 preset: https://github.com/UnlyEd/next-right-now/pull/210

**Comment by Vadorequest** [comment]
https://github.com/UnlyEd/next-right-now/pull/210 has been merged and applied to all v2 presets.

CI/CD was tested at https://github.com/UnlyEd/next-right-now/pull/210 and seem to work fine without any breaking/blocking issue.

**Comment by Vadorequest** [comment]
All occurrences of "now" and "zeit" have been changed to "vercel".

Applied on gh-pages and all v2 presets.

Thanks for your help!
