### ISSUE TITLE
Build Error Notification via Github Actions...

### ISSUE THREAD

**Issue by jajourda** [UnlyEd/next-right-now#19]
# Did this happen because I used npm instead of yarn?

![image](https://user-images.githubusercontent.com/1839603/77550769-dd42bc00-6e87-11ea-82e4-74463bdc5edc.png)

**Comment by Vadorequest** [comment]
This happens because you haven't configured a `token` Github variable for your project. 
See https://github.com/UnlyEd/next-right-now/tree/master/.github/workflows documentation

**Comment by jajourda** [comment]
# hmmm ... why did it work yesterday?
I was able to deploy yesterday...and now when I update the repo it won't build in zeit.
![image](https://user-images.githubusercontent.com/1839603/77580736-e301c700-6eb2-11ea-9805-00926e684bde.png)

**Comment by Vadorequest** [comment]
Because you probably deployed from your local computer using `yarn deploy`, which doesn't go through CI/CD and deploys directly to Zeit.

**Comment by jajourda** [comment]
# npm instead of yarn
could this cause problems for me in this repo? or is npm just fine?

**Comment by jajourda** [comment]
# How to set up next-right-now for Github Actions and Zeit

# 1. Go to  repo settings
Go to your repo's settings page and find the secrets tab.

# 2. Provide 2 Secrets to Github in your settings on the Secrets Tab

### 1. Generate a personal access token to copy and paste for later use:
![image](https://user-images.githubusercontent.com/1839603/77692868-c7172780-6f7d-11ea-851c-7e21d16e0075.png)

### 2. You may be asked to give/confirm your github password again:
![image](https://user-images.githubusercontent.com/1839603/77695293-e9ab3f80-6f81-11ea-92ec-e4300db9e426.png)


### 3. Create your First Secret for comments
#### 3.1 Navigate to Secrets and click ADD A NEW SECRET. Generate a new secret and name it `GITHUB_CI_PR_COMMENT`
![image](https://user-images.githubusercontent.com/1839603/77693028-0fcee080-6f7e-11ea-87f6-8fbbb85d016f.png)

#### 3.2 Head back over to your personal access tokens page and add a secret. Fill out the following fields. Write a note in the note field **it cannot be left blank**
![image](https://user-images.githubusercontent.com/1839603/77693653-127e0580-6f7f-11ea-8abe-284a7037555b.png)

#### 3.3 Select the following token scopes:
- all of repo
![image](https://user-images.githubusercontent.com/1839603/77693425-ae5b4180-6f7e-11ea-8d84-ed641f88511a.png)
- user > read:user
- user > user:email
![image](https://user-images.githubusercontent.com/1839603/77693451-bd41f400-6f7e-11ea-87da-aabe902bafff.png)
- workflow 
![image](https://user-images.githubusercontent.com/1839603/77693472-c7fc8900-6f7e-11ea-982d-3e1777c59820.png)
#### 3.4 Click the "Generate Token"
![image](https://user-images.githubusercontent.com/1839603/77695679-87067380-6f82-11ea-9226-ad459944c351.png)

#### 3.5 Copy your new personal access token by clicking the clipboard button next to your token string:
![image](https://user-images.githubusercontent.com/1839603/77694032-bd8ebf00-6f7f-11ea-9338-bc8ffd5a53a9.png)
#### 3.5 Paste your new personal access token into the textarea on your _Secrets_ tab and then click "Add Secret":
![image](https://user-images.githubusercontent.com/1839603/77694511-7fde6600-6f80-11ea-8268-b1512f1b6600.png)
#### 3.6 You should now see something like this:
![image](https://user-images.githubusercontent.com/1839603/77694579-a00e2500-6f80-11ea-8f81-d5cbf3a899dc.png)

### 4. Create Your Second Secret for Zeit
#### 4.1 Fill out **only** the note field for generating the next personal access token and generate the token.
![image](https://user-images.githubusercontent.com/1839603/77695883-dc428500-6f82-11ea-9531-d437523971d5.png)
#### 4.2 Add a New Secret on your secrets tab and give it the name `ZEIT_TOKEN`. Paste the value of your newly copied second secret into the provided text area and click "Add Secret"
![image](https://user-images.githubusercontent.com/1839603/77696072-2fb4d300-6f83-11ea-9df7-d4b77f2cf282.png)
#### You should now see this in your secrets tab
![image](https://user-images.githubusercontent.com/1839603/77696174-5410af80-6f83-11ea-90e6-85965aa0ce88.png)

**Comment by jajourda** [comment]
# It still fails after putting in tokens as described above
![image](https://user-images.githubusercontent.com/1839603/77696590-0183c300-6f84-11ea-9e3e-99bf5592d218.png)

**Comment by Vadorequest** [comment]
The error has changed, you've fixed the token issue.

The team specified in your now.*.json file isn't yours, you should use the `projectId` in your `.now/project.json` file

**Comment by jajourda** [comment]
I added ran `yarn build` and i ran `npm run build`.

I got this result locally.

![image](https://user-images.githubusercontent.com/1839603/77705394-f174df00-6f95-11ea-8b4c-e7b792334d29.png)

**Comment by Vadorequest** [comment]
@jajourda You've got to read error messages. The error is self-explanatory here.

Sentry DSN isn't defined, look at your `SENTRY_DSN` env var in .env.build file

**Comment by jajourda** [comment]
@Vadorequest , sorry, i mixed up sentry with locize and amplitude based on memory of older docs from an older commit. I was confused after reading the error because of the docs and this memory mixup:

> Tip: You could use any value for LOCIZE_API_KEY, AMPLITUDE_API_KEY because the app would still work even if those values are wrong. But associated features won't work correctly.

My `SENTRY_DSN` property is empty in my .env.build file. but it is present in my now.json file. i copy my value from the now.json file and paste it into  my .env.build file as well.

**Comment by Vadorequest** [comment]
Empty won't do, tests expect a valid value to pass.

But it's a misc error, it doesn't affect how the app actually works, it just impacts the tests suite.

**Comment by Vadorequest** [comment]
@jajourda Is this resolved?

**Comment by jajourda** [comment]
Not yet. My plan is to try to work through the documentation and step-by-step successfully install and configure next-right-now E2E. I will try to work my insights into my own branch on my forked next-right-now repo. Hopefully I can make this into a pull request.

https://github.com/jajourda/next-right-now/tree/jajourda-docs

**Comment by Vadorequest** [comment]
Awesome, I'm sure your insights will help polish the current "getting started" workflow to help polish angles for an easier/better developer experience :)

**Comment by jajourda** [comment]
@Vadorequest  https://github.com/UnlyEd/next-right-now/pull/22#issuecomment-606247617

**Comment by Vadorequest** [comment]
@jajourda Closing this, I believe it's fixed. Let me know otherwise.
