### ISSUE TITLE
Docs Site via Github Pages

### ISSUE THREAD

**Issue by jajourda** [UnlyEd/next-right-now#20]
# Build a Documentation Site via Github Pages
Circa the discussion in https://github.com/UnlyEd/next-right-now/issues/18#issuecomment-603991162, it seems a fitting task to make a documentation website.

## Resources
Here is one approach.
https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/

![alt text](https://github.blog/wp-content/uploads/2016/08/47c5a586-6533-11e6-982c-ebd41ec6968c.gif)

### An example of this is the Jekyll repo itself
You can see it here:
https://github.com/jekyll/jekyll/tree/master/docs

## You said you were busy...
I don't mind taking a stab at building a simple docs jekyll site that I add to. This would of course require some kind of repo access. If you're uncomfortable with that, I can take a stab at trying to build my own github pages approach that you link to (but you will miss out on the tight coupling with your own repo and the ability to incorporate issues and pull requests)
> Most importantly, using GitHub Pages means your documentation lives alongside your code on GitHub, where you can use things like Issues and Pull Requests to ensure it receives the high level of care it deserves; and because GitHub Pages lets you publish from the /docs directory on the master branch, you can maintain your codebase and its published documentation on the same branch.

**Comment by jajourda** [comment]
#an idea...
I could also make a fork of the next-right-now repo, add "docs" directory and you could give oversight via deciding to incorporate the pull request or not

**Comment by jajourda** [comment]
# here's what publishing looks like

![alt text](https://github.blog/wp-content/uploads/2016/08/47c2ecc4-6533-11e6-828a-91980daa7297.gif)

**Comment by Vadorequest** [comment]
Thanks! It's really straightforward. I like the /docs options, it's the cleanest IMHO because it lives with the source code itself as you stated, easier to maintain and keep up to date!

I've released a very basic "hello word" -ish version:
https://unlyed.github.io/next-right-now/

So, now let's decide what should be part of the README.md and what should be part of the /docs folder 🤔 

I think the README should be kept minimal and only provide an overview without going into technical details.

I'm thinking about the following structure:
- Overview
- Benefits
- Variants (index of all the variants as explained in #18 
- ToC
- Overview of Next Right Now
- Documentation (basically a link toward the github docs site)
- FAQ
- License
- Vulnerability disclosure
- Contributors and maintainers
- [ABOUT UNLY]

So, we'd keep only what gives an overview, and move all the technical into the docs.
@jajourda What are your thoughts on this structure?

**Comment by Vadorequest** [comment]
@jajourda I've started to work on this at https://github.com/UnlyEd/next-right-now/pull/17

Here is what the structure looks like for now, any feedback/suggestions?
![image](https://user-images.githubusercontent.com/3807458/77646051-15b7c800-6f64-11ea-9b7f-02554f87bdbe.png)

**Comment by Vadorequest** [comment]
@jajourda I've merged the new docs version and it's available at https://unlyed.github.io/next-right-now/

I could use your help with the navigation menu, I'd love your feedback/contribution about how to build it. I've looked at Jekyll a bit but since you have some experience, I believe your input would be much valuable.

**Comment by jajourda** [comment]
I just looked at it. the roadmap looks cool. out of curiosity why did you go with the architect?

https://github.com/pages-themes/architecthttps://github.com/pages-themes/architect

**Comment by jajourda** [comment]
so far the file structure looks great! i'm excited to see it fleshed out.

**Comment by Vadorequest** [comment]
Just found the tuto to install it locally https://help.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll gonna try it out

**Comment by Vadorequest** [comment]
I chose Architect because I liked the way it looks. Do you have another proposition?

**Comment by jajourda** [comment]
first a question: did you choose to go with github pages themes because of the ease of just citing the theme in config.yaml and then being done?

**i.e. to avoid having to code layouts?**

**Comment by jajourda** [comment]
#### an additional suggestion
I would suggest having a well-styled, non-text heavy home page that better visually divides the content you are trying to highlight and showcase.

**Comment by Vadorequest** [comment]
>first a question: did you choose to go with github pages themes because of the ease of just citing the theme in config.yaml and then being done?



I didn't really think through about that, I supposed using a predefined theme would be less work

**Comment by Vadorequest** [comment]
The content of the documentation itself will need to we improved indeed, I basically copied/pasted existing content to fill the blanks, but I do intend to improve it

**Comment by jajourda** [comment]
# my suggestion

Jekyll's layouts are really powerful in helping code to by DRY. for this reason i recommend a different route that requires a **bit** more work on the frontend:

https://github.com/BlackrockDigital/startbootstrap

specifically the templates folder
https://startbootstrap.com/templates/

I would build between 3-5 layout .md files based on templates that suited the needs to have more fine-grained control over presenting the docs material.

**Comment by jajourda** [comment]
# navigation

build a .md file in your _includes directory and either hard code the items into your nav, or create a dynamic nav doing some derivation of this approach:

https://talk.jekyllrb.com/t/how-to-create-a-dynamic-menu-in-jekyll-that-auto-populates-nav-items-when-creating-new-pages/2141

**Comment by Vadorequest** [comment]
Regarding layouts, I don't understand how Jekyll and SB are related. How are we supposed to install one of those? What benefits/constraints does it brings?

**Comment by Vadorequest** [comment]
I'm thinking about https://github.com/pmarsceill/just-the-docs as Jekyll theme, what do you think?

**Comment by jajourda** [comment]
# great choice
Just the docs looks great!

**Comment by jajourda** [comment]
I would still recommend giving tlc to the home page. For now I don't want to impede your progress, I just want to increase readibility and liklihood of adoption 😄

**Comment by Vadorequest** [comment]
Thanks for the quick feedback! https://unlyed.github.io/next-right-now/ looks much better already

**Comment by jajourda** [comment]
This seems like it will help you. It looks like they recommend putting your docs into the _pages directory when you get started populating.

https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/

**Comment by jajourda** [comment]
# stylesheets are missing

![image](https://user-images.githubusercontent.com/1839603/77690407-9d5c0180-6f79-11ea-8c4c-a61bcf3b63b4.png)


![image](https://user-images.githubusercontent.com/1839603/77690433-a64cd300-6f79-11ea-8305-64bca18bf46b.png)

## missing directories revealed in link elements
![image](https://user-images.githubusercontent.com/1839603/77690572-e57b2400-6f79-11ea-9c10-ee94bee67647.png)

### where is your assets folder?
![image](https://user-images.githubusercontent.com/1839603/77690626-faf04e00-6f79-11ea-920c-1ec1ae39f2c0.png)

**Comment by Vadorequest** [comment]
Yes I know, that's because it's complicated to make it work both locally and on GitHub Actions... Much harder than it should be.

**Comment by Vadorequest** [comment]
I've fixed the issue on GHP. https://unlyed.github.io/next-right-now/

**Comment by Vadorequest** [comment]
I've made possible to run jekyll locally, it now behaves the same whether running on GHP or locally.
This was a much-needed feature for documentation maintenance ease

![image](https://user-images.githubusercontent.com/3807458/77701938-a8358700-6fb7-11ea-8b45-9fcb1b6c4669.png)

**Comment by jajourda** [comment]
# 404 Page Not Flound for home page

The other pages and nav links appear to be working.

![image](https://user-images.githubusercontent.com/1839603/77705437-0ea9ad80-6f96-11ea-9f87-d0429617ddfb.png)

**Comment by jajourda** [comment]
# consider indenting and categorizing nav links 
It would make site content divisions more apparent if you indent sub links in the left nav column

**Comment by Vadorequest** [comment]
Please avoid using H1 title for no valid reason.

Work regarding documentation is being done in this PR: https://github.com/UnlyEd/next-right-now/pull/21

**Comment by Vadorequest** [comment]
@jajourda Check https://unlyed.github.io/next-right-now/CONTRIBUTING.html if you want to contribute to the doc. 😉 

I think the next step is for me to go through the doc and improve them massively. Do you have any feedbacks regarding the current version? (besides what you already told me)
Bullet points would be great 😄

**Comment by jajourda** [comment]
@Vadorequest , i took a look at the contributing file. I will try to make a pull request if I find anything that will make the project clearer or more adoptable. 

I was using h1 as a TLDR for future readers of the issue who may only want to scan 😄

**Comment by Vadorequest** [comment]
@jajourda I recommend you don't work on the docs until this PR is merged, to avoid conflicts
https://github.com/UnlyEd/next-right-now/pull/22
