### ISSUE TITLE
TS error on SSG

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#203]
After merging last changing in I'm getting this ts error on SSG:

```
Type '(context: any) => Promise<StaticPathsOutput>' is not assignable to type 'GetStaticPaths<CommonServerSideParams<ParsedUrlQuery>>'
```

<img width="1257" alt="Screen Shot 2020-11-19 at 10 40 21 AM" src="https://user-images.githubusercontent.com/5281701/99709249-c9217f80-2a53-11eb-947d-b584489e8968.png">

**Comment by Vadorequest** [comment]
Did you run into conflict?

I can't help much on this, you'll need to go through the commits yourself and see what was changed and how it might impact your fork.

Related to the changes Next 10 made to their typings. See https://github.com/UnlyEd/next-right-now/pull/190

**Comment by Vadorequest** [comment]
Mainly related to [`b30dda8` (#190)](https://github.com/UnlyEd/next-right-now/pull/190/commits/b30dda88fa8f31599d94a030ed246bfcc230ca3a)

**Comment by samuelcastro** [comment]
Yeah, after building it went away, probably some cache or something else.
