### ISSUE TITLE
TSX files needs to have a React import

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#204]
A few files are not importing React, the one I noticed was: `MultiversalGlobalStyles`

```
(JSX attribute) GlobalProps<any>.styles: InterpolationWithTheme<any>
'React' must be in scope when using JSX eslintreact/react-in-jsx-scope
```

More info: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md

<img width="964" alt="Screen Shot 2020-11-19 at 10 50 30 AM" src="https://user-images.githubusercontent.com/5281701/99710696-bc059000-2a55-11eb-8edd-5e659b5b02de.png">

Again, after last pull.

**Comment by Vadorequest** [comment]
Yeah, there is some issues about this that aren't directly related to NRN. See https://github.com/vercel/next.js/issues/18096#issuecomment-729868888

I didn't spot this, though (or, did I fix it on my private fork but forgot to fix it in NRN? 🤔 ). 

I believe you can remove that particular rule from your project (`react/react-in-jsx-scope`) in eslintrc. As React is no longer needed.

Stuff to do with Babel, TypeScript and other complicated stuff. As long as it compiles fine, the eslint rule can be removed.

**Comment by samuelcastro** [comment]
Isn't better keep the rule and import React consistently just like the rest of the project?

**Comment by Vadorequest** [comment]
Not if it's not necessary. It was only done before because it was a requirement, but it's not the case anymore.

Also, code linters always complained about React being imported yet unused.

**Comment by samuelcastro** [comment]
ok.
