### ISSUE TITLE
Migrate `v2-mst-aptd-gcms-lcz-sty` preset to GraphCMS v2 - GraphCMS v1 terminated on February 1st 2021

### ISSUE THREAD

**Issue by Vadorequest** [UnlyEd/next-right-now#211]
The `v2-mst-aptd-gcms-lcz-sty` preset uses GraphCMS v1.

The v1 will be terminated on February 1st, 2021.

Once the v1 is terminated, **the preset will become unusable**, both locally and online (preview/production).

**We need to migrate the v2, or find a different alternative to GraphCMS.** 

The v2 has multiple breaking changes that'll impact the current implementation, such as:
- Content stages
- i18n

Also, I need to negotiate the new v2 project to be free for NRN, which is what I negotiated with them since the beginning (v1). Shouldn't be a problem, but yet another thing to take care of.

### Disclaimer:
I'm not personally using GraphCMS anymore, nor using a private fork of the `v2-mst-aptd-gcms-lcz-sty` preset, and therefore will most likely not have the interest nor time to work on this at all. 

If the `v2-mst-aptd-gcms-lcz-sty` preset becomes unusable, I'll have no other choice than deprecate it.

If you know a free alternative to GraphCMS that could be used to replaced GraphCMS as a GraphQL endpoint, please share. Also, I believe the community will need to work on this and maintain it, as I do not intend to maintain it past 2020.

> Please upvote this if you wish the preset to be maintained somehow, that'll help me understand how many people are interested in it. I have no clue about how many people actually use it.

**Comment by samuelcastro** [comment]
> Also, I need to negotiate the new v2 project to be free for NRN, which is what I negotiated with them since the beginning (v1). Shouldn't be a problem, but yet another thing to take care of.

What do you mean? Isn't it already free for dev usage: https://graphcms.com/pricing

**Comment by samuelcastro** [comment]
I really would like `v2-mst-aptd-gcms-lcz-sty` to be maintained moving forward, I'm using it and I believe it would be of interest of many to see a 100% GraphQL solution like this.

**Comment by Vadorequest** [comment]
> What do you mean? Isn't it already free for dev usage: graphcms.com/pricing

The free plan provides neither i18n support, nor multiple stages. And IMHO, i18n support is a must have for the NRN demos.

**Comment by Vadorequest** [comment]
@samuelcastro FYI I've been working on https://github.com/UnlyEd/next-right-now/pull/216 to migrate the demo to GraphCMS v2. It's ready and I'll probably merge it today.

**Comment by Vadorequest** [comment]
Resolved by #216
