### ISSUE TITLE
The flag for English is incorrect

### ISSUE THREAD

**Issue by jordie23** [UnlyEd/next-right-now#244]
**Describe the bug**
The flag you have to represent English is the flag of Great Britain from 1606 that was changed in 1801. It should be updated to the modern day UK flag, or use a hybrid EN/US flag like https://i.imgur.com/JJdzMnX.png

**To Reproduce**
1. Go here https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-gcms-lcz-sty/src/svg/EnglishFlag.svg
2. See it's not the UK flag.

**Expected behavior**
To use the correct flag. See more here, https://en.wikipedia.org/wiki/Flag_of_the_United_Kingdom - you can see on the diagram you have "King's Colours of 1606 / 1707 (Great Britain)"

**Comment by Vadorequest** [comment]
Thanks for letting us know! I'll tell our designer that'll surely give him a good laugh 🤣

**Comment by Vadorequest** [comment]
@jordie23 Fixed in #250. Demo at https://nrn-v2-mst-aptd-at-lcz-sty-c1-preview.vercel.app/en
