### ISSUE TITLE
Why custom I18nLink ?

### ISSUE THREAD

**Issue by Jbmanllr** [UnlyEd/next-right-now#254]
Hello, is there a reason you created a custom I18nLink when next js offer it natively: https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by Vadorequest** [comment]
Next Right Now doesn't use the native i18n routing implementation of Next.js.

https://unlyed.github.io/next-right-now/guides/i18n/#official-i18n-routing-implementation

I hope this answers the question! 
Closing this, let me know if it doesn't. 😄
