### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#278]
**Describe the bug**
I'm getting this error when building locally:

```terminal
> Build error occurred
TypeError: Cannot read property 'substring' of undefined
```

**To Reproduce**
1. run `yarn build`

**Expected behavior**
Be able to successfully build.

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by samuelcastro** [comment]
Fixed here: https://github.com/UnlyEd/next-right-now/pull/279

**Comment by Vadorequest** [comment]
Fixed by https://github.com/UnlyEd/next-right-now/pull/281
