### ISSUE TITLE
Windows `yarn start` failure

### ISSUE THREAD

**Issue by Vadorequest** [UnlyEd/next-right-now#286]
**Describe the bug**
It seems Windows doesn't like the `. ./` used by the `yarn start`, we should make it Windows compatible.

Feedback provided by other people, I haven't tested myself, but something doesn't seem to work properly.

**Comment by adreszer** [comment]
Confirmed, doesn't work. 
`$ . ./scripts/populate-git-env.sh && next dev --port 8888
'.' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by Vadorequest** [comment]
@adreszer Thank you, I've started working on it at #293

**Comment by Vadorequest** [comment]
@adreszer The easiest workaround for Windows is to run `next dev --port 8888` directly.

Basically, avoid running the .sh file before starting the server will work fine. A few Git metadata won't be available though, but it shouldn't be an issue.

We could add a script like 
```
    "start:windows": "next dev --port 8888",
```

If that makes sense and might help??

**Comment by Vadorequest** [comment]
Another alternative is to use WSL.

https://www.thewindowsclub.com/how-to-run-sh-or-shell-script-file-in-windows-10

**Comment by adreszer** [comment]
> @adreszer The easiest workaround for Windows is to run `next dev --port 8888` directly.
> 
> Basically, avoid running the .sh file before starting the server will work fine. A few Git metadata won't be available though, but it shouldn't be an issue.
> 
> We could add a script like
> 
> ```
>     "start:windows": "next dev --port 8888",
> ```
> 
> If that makes sense and might help??

I think this is worth adding and mentioning in the docs, might help a lot of people avoid first-contact frustration :) Cheers!

**Comment by Vadorequest** [comment]
Done! Thanks for the quick feedback.
