### ISSUE TITLE
Improve Layouts organization

### ISSUE THREAD

**Issue by Vadorequest** [UnlyEd/next-right-now#307]
I find it a bit hard to use the Layouts correctly at this time (`src/layouts`)

I'm working on a new project based on the latest version of NRN and the "default" layout didn't make sense to me. Also, it was simply forwarding the "core" components, which didn't provide much value.

Eventually, I renamed the "default" to "public", meant to be used for all pages that don't require authentication.

And I added a new layout "builder" for the "builder" part of my app, which is behind authentication.
I intend to have the "builder" layout check for authentication by default, and automatically redirect to the homepage if the user isn't authenticated. This will ensure all my "/builder" pages are protected by default.

![image](https://user-images.githubusercontent.com/3807458/113476438-d461ce80-947b-11eb-9f19-1126f6b3af2e.png)

I also removed some "core" layout components, and I would rather rename the "core" layout to "base", because "core" makes me feel like I shouldn't change it.

Also, all "layouts/core/types" types should probably be prefixed with "core", because different layout might very likely describe different props types for pages using those layouts. ("builder" pages would be provided with the authenticated user, while "public" pages wouldn't).

Also, I added one template file per layout per rendering mode.

> **Note to self**: It's easier to make sense of how layouts should be used with a real use-case. Adding authentication to the NRN example would help making sense of this advanced feature. The above "builder" layout could be renamed to something like "back-office" or "auth" which are more common.

**Comment by samuelcastro** [comment]
Are you planning to create a PR and include this?

**Comment by Vadorequest** [comment]
Yeah, eventually. It'll be included in a bunch of other improvements once I'm done with the said project. (ETA 3-4 months)

**Comment by Vadorequest** [comment]
Some work has been done in https://github.com/UnlyEd/next-right-now/pull/330 and https://github.com/UnlyEd/next-right-now/pull/331 a few weeks ago.

I find it easier to customise NRN when using it as a boilerplate now. It's also less confusing. I have kept the "core" naming for now. I'm closing this, let me know if things should be improved further.
