### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by gnovotny** [UnlyEd/next-right-now#309]
The preset v2-mst-aptd-at-lcz-sty has performance issues that are unfortunately not self-evident due to the lightness of the demo. To see what I mean, go to [https://nrn-v2-mst-aptd-at-lcz-sty-c1.vercel.app/en/terms](https://nrn-v2-mst-aptd-at-lcz-sty-c1.vercel.app/en/terms), open the Elements tab in developer tools and navigate back and forth between the landing and term pages. I believe that cookieconsent is not the only thing being reinitialised with every re-render.

**Comment by Vadorequest** [comment]
Could you explain exactly what's wrong and what you'd expect? Cookie consent is only enabled on the terms/privacy pages.

**Comment by gnovotny** [comment]
I think the main issue is _BrowserPageBootstrap_ calling _initCookieConsent_  (assuming cookie consent is displayed on all pages) and _getAmplitudeInstance_ with each nextjs route change. If your machine is not very powerful and you are running multiple browser extensions (some of which block amplitude), then this can cause some massive overhead and progressively reduce the responsiveness of the website with each route change. In the case of _initCookieConsent_, it also pollutes the DOM with an additional cookieconsent element for each route change you make.

**Comment by Vadorequest** [comment]
Thank you for the detail, I understand the issue better now. I wasn't aware of this.

Regarding Amplitude, I'm not sure what could/should be done. At least one event is sent per page transition, it should trigger when there is a route change. Do you have any recommendation about this?

Regarding initCookieConsent, it obviously shouldn't pollute the DOM. I think it might be instanciated on every page, although it's only displayed on a few. I'll take a look at it.

**Comment by gnovotny** [comment]
My quickfix for _initCookieConsent_ was to wrap it in a _useEffect()_. I don''t know if the same can (or should) be applied to _getAmplitudeInstance_ though.

**Comment by Vadorequest** [comment]
That's a good fix. I've written most of NRN when I wasn't familiar with `useEffect`, that's probably how I'll fix it too!

Would you like to make a PR? Let me know.

**Comment by samuelcastro** [comment]
Good catch on this.

**Comment by samuelcastro** [comment]
Just fyi, `useEffect` does not support SSR.

**Comment by Vadorequest** [comment]
SSR doesn't matter for this, because it's a frontend plugin anyway and relies on frontend package (not SSR compatible).

PR: https://github.com/UnlyEd/next-right-now/pull/319

**Comment by Vadorequest** [comment]
@gnovotny I checked the code and I don't think there is anything else to optimise besides CookieConsent. It's the only browser-only module built-in.

**Comment by Vadorequest** [comment]
@gnovotny Using `useEffect` is not the proper way to deal with this issue, it has side effects you probably didn't notice.

I made an implementation at https://nrn-v2-mst-aptd-at-lcz-sty-c1-914c76hdd-unly-oss.vercel.app/ and going to /privacy without doing a full page reload won't show the cookie consent pop-up.

---

A different implementation is being tested on https://github.com/UnlyEd/next-right-now/pull/319 and has been deployed at https://nrn-v2-mst-aptd-at-lcz-sty-c1-8eqe6ezlv-unly-oss.vercel.app/en

**Comment by Vadorequest** [comment]
Done in https://github.com/UnlyEd/next-right-now/pull/319, closing.

Let me know if it doesn't work out as it should.
