### ISSUE TITLE
SSG Support

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#37]
So you're adding `getInitialProps` on `_.app.tsx` meaning that there is no SSG support, are you planning to change this to a more dynamic way to suport SSG and SSR?

Thanks!

**Comment by Vadorequest** [comment]
Yes, it's something that I want to do. My current business setup uses this SSR variant, but I plan on moving it to SSG for various reasons. It's definitely something I want to support.

See https://unlyed.github.io/next-right-now/concepts/presets#which-presets-are-being-considered

**Comment by samuelcastro** [comment]
That's great, what's the deadline for that?

**Comment by Vadorequest** [comment]
Not really, it's amongst the tons of things I have to do ASAP 😄
