### ISSUE TITLE
GraphCMS needs Bearer in authorization request

### ISSUE THREAD

**Issue by sovattha** [UnlyEd/next-right-now#40]
When deployed in `eu-central-1`, GraphCMS returns an HTTP 400 if the `authorization` header is set without the `Bearer` prefix.

The sample application uses `api-euwest` which still accepts an authorization header set directly.

I provided a fix with the [pull request 39](https://github.com/UnlyEd/next-right-now/pull/39).

**Comment by Vadorequest** [comment]
Fixed in both master and main preset branch.
