### ISSUE TITLE
in Windows 10, it doesn't work.

### ISSUE THREAD

**Issue by n00nietzsche** [UnlyEd/next-right-now#55]
I just did things to get started for this.

but i got this message

```
IWAZ@JINKYU MINGW64 ~/Desktop/my-project/react-blog-2020_NRN (master)
$ yarn start
yarn run v1.22.4
$ now dev --listen 8888
> UPDATE AVAILABLE Run `yarn add now@latest` to install Now CLI 19.0.1
> Changelog: https://github.com/zeit/now/releases/tag/now@19.0.1
> Now CLI 16.7.3 dev (beta) — https://zeit.co/feedback
> Creating initial build
The system cannot find the path specified.
child_process.js:122
  p.open(fd);
    ^

Error: EBADF: bad file descriptor, uv_pipe_open
    at Object._forkChild (child_process.js:122:5)
    at setupChildProcessIpcChannel (internal/bootstrap/pre_execution.js:338:30)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:54:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -4083,
  code: 'EBADF',
  syscall: 'uv_pipe_open'
}
Done in 24.83s.
```

when i installed this on my Mac laptop, it worked well.

it's a really shame that i can't run this on my window laptop.

**Comment by Vadorequest** [comment]
`The system cannot find the path specified.`

This seems to be a Next.js related error. Also, I really can't debug this with so little information. Also, I don't really intend of supporting Windows by myself, because I don't use it and can't test it.

I'm open to contributions though, but it has never run under windows and there are millions of reasons it may fail on it.

I suggest you report this bug to Next.js and see if it's Next.js or NRN related, that'd help. If you find a fix, I'll try to merge it.

**Comment by n00nietzsche** [comment]
Thanks for rapid response. I actually solved 'The system cannot find the path specified.' issue. 

it was my PATH environment variable problem.

but it still doesn't work.

so i decided to use wsl2 to run this in Windows. 

anyone want this to run in Windows. just use wsl2. it would be much comfortable.

**Comment by Vadorequest** [comment]
Glad to know you found how to fix this!

Was it related to Next.js, or NRN? Would you mind contributing to the documentation (`gh-pages` branch) and add your question/answer to the [FAQ](https://unlyed.github.io/next-right-now/faq)? (see https://unlyed.github.io/next-right-now/contributing)

**Comment by Vadorequest** [comment]
@n00nietzsche The new NRN v2 version supports Windows 8/10 out of the box, I tested it today. Doc has been updated.

**Comment by n00nietzsche** [comment]
> @n00nietzsche The new NRN v2 version supports Windows 8/10 out of the box, I tested it today. Doc has been updated.

Thanks a lot!!!
