### ISSUE TITLE
GraphCMS Locale fallback

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#62]
Searching about locale fallback I came across this https://graphcms.nolt.io/35, and I noticed you're not using `gcms-locale` is it just because of the limitation of the locale in the free version of GraphCMS? 

Isn't it better to add it and include the supported default supported locales we have even though it might not make effect for a free account at least people will know this is available.  

Maybe I just misunderstood this.

**Comment by Vadorequest** [comment]
Actually, it's already how it works! 😉 

https://github.com/UnlyEd/next-right-now/blob/d1204230db011189ff262ee3e9284a024f9a47f0/src/utils/nextjs/SSG.ts#L54

The current behaviour is to use [selectedLanguage, alternativeLanguage] (e.g: `['FR', 'EN']`) if the page you visit is in `fr`.

This way, it'll select FR content and then fallback to EN content if FR isn't defined.

**Comment by samuelcastro** [comment]
Oh, I missed it, I was looking this file: https://github.com/UnlyEd/next-right-now/blob/v1-hyb-mst-aptd-gcms-lcz-sty/src/utils/gql/graphql.ts#L15

Thanks!
