### ISSUE TITLE
Use .env instead of .env.build file

### ISSUE THREAD

**Issue by Vadorequest** [UnlyEd/next-right-now#67]
# Motivations

Next has recently released a new way to handle env variables.

The migration to .env instead of .env.build would allow to use `next dev` instead of `now dev`. 

This change may fix the current "Next.js dev server gets stuck after a while, requests just spin" (see https://github.com/vercel/vercel/issues/3612#issuecomment-635430002)

Also, it would allow to run Next in debug mode using `NODE_OPTIONS='--inspect' next`, which is necessary for VSCode IDE to be able to attach its debug process.  (see https://github.com/vercel/next.js/pull/10807)

Also, the recent `NEXT_PUBLIC_` env variables is meant to make it more obvious what ENV vars are shared with the browser, and this would increase transparency and understanding.

Overall, the dev experience may become better.

# Concerns
Needs to be compatible with Vercel. No idea what issues might be encountered.

---

Current:
https://nextjs.org/docs/api-reference/next.config.js/environment-variables

New:
- https://nextjs.org/docs/basic-features/environment-variables

**Comment by samuelcastro** [comment]
This would be great, I was going to open up an issue, glad you did it.

**Comment by Vadorequest** [comment]
Also thinking of the new NEXT_PUBLIC_* env variables, will to see if I can integrate this as well.

**Comment by Vadorequest** [comment]
@samuelcastro WIP at https://github.com/UnlyEd/next-right-now/pull/77, could use your review! :)

Much easier than expected, let me know what you think.

**Comment by Vadorequest** [comment]
Closing, has been merged and fully functional.

It has reduced the pain for getting started with NRN, so that's great!
