### ISSUE TITLE
Use with-graphql-hooks instead of Apollo (reduce bundle size)

### ISSUE THREAD

**Issue by Vadorequest** [UnlyEd/next-right-now#72]
with-graphql-hooks may be an alternative to the current implementation

See https://github.com/vercel/next.js/tree/canary/examples/with-graphql-hooks

Main interest would be to reduce the bundle size (for all pages)

I'll give it a try at some point, if nobody does it first 😉

**Comment by samuelcastro** [comment]
Keep in mind that pages using SSR/SSG will not be able to use react hooks, so probably you'd need this: https://github.com/nearform/graphql-hooks/tree/master/packages/graphql-hooks-ssr

**Comment by Vadorequest** [comment]
Good point!

It's true actually that all pages only fetch data from the server side, whether SSR/SSG, none of them does it from the client side.

**Comment by Vadorequest** [comment]
Closing this since as mentioned above it wouldn't fit the current use case outside of functional components (e.g: getStaticProps/getServerSideProps)
