### ISSUE TITLE
Preview Mode + Security

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#85]
Are you planning to implement any security check on preview mode, like: https://nextjs.org/docs/advanced-features/preview-mode#securely-accessing-it-from-your-headless-cms

I was looking to see how GraphCMS handles it but couldn't find much, just https://docs.graphcms.com/docs/guides/preview-environment-flow.

**Comment by samuelcastro** [comment]
This explains my question: https://github.com/vercel/next.js/discussions/13589

**Comment by Vadorequest** [comment]
Maybe that should be explained in the preview page though?

**Comment by samuelcastro** [comment]
Yeah, like I needed to do some research to understand the whys of the current implementation. so more information is important.

**Comment by samuelcastro** [comment]
Re-opening this for now until more information is added.

**Comment by Vadorequest** [comment]
Where would you see such doc being added?

**Comment by samuelcastro** [comment]
There are many places that a documentation would help, some comments on https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-gcms-lcz-sty/src/pages/api/preview.ts, also in the oficial docs and preview examples.

I think just explaining why the token security is not required on GraphCMS or the limitations of it would be super helpful.

**Comment by Vadorequest** [comment]
Alright, let me know if you have time to make a documentation PR towards https://github.com/UnlyEd/next-right-now/tree/v2-mst-aptd-gcms-lcz-sty branch. Otherwise I'll try to find the time to do it.

Thanks for you feedback!

**Comment by samuelcastro** [comment]
I can help with it, I'm busy these days but I'll find sometime.

**Comment by Vadorequest** [comment]
@samuelcastro I'll work on this soon, self-assigning.

**Comment by samuelcastro** [comment]
Ok sounds good.

**Comment by Vadorequest** [comment]
Done in https://github.com/UnlyEd/next-right-now/commit/07c491ad720e23501fea9219f9375ef8f55aec2f
