### ISSUE TITLE
Font preload

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#89]
You're preloading fonts with:

```html
<link rel="preload" as="font" href={'/static/fonts/NeuzeitGrotesk/font.css'} />
```

But I think it should actually be:
```html
<link rel="preload" href="/static/fonts/NeuzeitGrotesk/NeuzeitGrotesk-regular.woff2" as="font" type="font/woff2"> 
```

https://web.dev/codelab-preload-web-fonts/

**Comment by Vadorequest** [comment]
Thanks, indeed I'm a bit confused about the right way of doing things.

I've opened an issue at https://github.com/GoogleChrome/lighthouse/issues/10892#issuecomment-637086968

But, I believe `preload` doesn't play nicely with `WebFontLoader` somehow.
See https://github.com/typekit/webfontloader/issues/403

**Comment by jeantil** [comment]
out of curiosity is there a specific reason for not using [font-display: swap]( https://developers.google.com/web/updates/2016/02/font-display) and using a js loader instead ?

**Comment by Vadorequest** [comment]
font-display: swap is actually being used, but not available on all browser, this was supposed to use the best of both worlds to avoid FOUT effect and blinking text.

**Comment by samuelcastro** [comment]
@jeantil https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-gcms-lcz-sty/public/static/fonts/NeuzeitGrotesk/font.css#L13

**Comment by Vadorequest** [comment]
Fixed by https://github.com/UnlyEd/next-right-now/pull/97
