### ISSUE TITLE
understanding the purpose of logger

### ISSUE THREAD

**Issue by crisfcodes** [UnlyEd/next-right-now#93]
https://github.com/UnlyEd/next-right-now/blob/0ceea3f3f46cfbd9dc9707b7fc119725319f7592/src/pages/404.tsx#L16

What is the purpose of creating a `logger` in some pages? in webstorm i have a lot of warnings from ts compiler `TS6133: 'loger' is declared but its value is never read`. Is it only there to be used if necessary?

--------------------------------------

There is a lot of `console.*` in pages as `/src/pages/_error.tsx/` according to this [rule](https://github.com/UnlyEd/next-right-now/blob/0ceea3f3f46cfbd9dc9707b7fc119725319f7592/.eslintrc.yml#L45) I should replace it with `logger`.

**Comment by Vadorequest** [comment]
The logger doesn't log stuff that aren't `error` on production.

It basically avoids cluttering the server with logs. I had done that from a time where I was paying for logs, which isn't the case anymore (AFAIK).

But, it's not the best implementation, and it's not lightweight either (see https://github.com/UnlyEd/next-right-now/issues/49).

Eventually, it'll evolve, it's just not my main priority.

Also, it's defined "in case of", but I'd rather see a globally available object, or something that doesn't need to be reconfigured per-file. I haven't found how to to that properly yet, despite multiple attempts.

My recommendation: Ignore it for now, it's no big deal and wont change anything (but if you do make change, you'll eventually run into useless conflicts if you ever re-pull once I've changed the implementation)

**Comment by Vadorequest** [comment]
@cristian05  Closing, let me know if it doesn't answer your question.
